language: rust
cache: cargo
os:
  - osx
  - linux
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all --release
  - cargo test --verbose --all --release
  - cargo install --path=. --force

matrix:
  allow_failures:
    - rust: nightly
