[package]
name = "cargo-with"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
clap = "2.32.0"
failure = "0.1.3"
log = "0.4.5"
env_logger = "0.5.13"
